import { generatedName } from './generatedName';

export let nameData: generatedName[] = [
  {
    id:0o1,
    factionName:'Aquila',
    factionImageTop:'./assets/images/cardBackgrounds/AquilaTop.png',
    factionImageBottom:'./assets/images/cardBackgrounds/AquilaBottom.png',
    name1:'Sam',
    name2:'Porter',
    name3:'Karter',
    fullName:'Sam Porter Karter',
  },
  {
    id:0o2,
    factionName:'Pendzal',
    factionImageTop:'./assets/images/cardBackgrounds/PendzalTop.png',
    factionImageBottom:'./assets/images/cardBackgrounds/PendzalBottom.png',
    name1:'Vlad',
    name2:'Decker',
    name3:'',
    fullName:'Vlad Decker',
  },
  {
    id:0o3,
    factionName:'Sona',
    factionImageTop:'./assets/images/cardBackgrounds/SonaTop.png',
    factionImageBottom:'./assets/images/cardBackgrounds/SonaBottom.png',
    name1:'Achmed',
    name2:'Ibn-Leru',
    name3:'',
    fullName:'Achmed Ibn-Leru',
  },
  {
    id:0o4,
    factionName:'Ekanesh',
    factionImageTop:'./assets/images/cardBackgrounds/EkaneshTop.png',
    factionImageBottom:'./assets/images/cardBackgrounds/EkaneshBottom.png',
    name1:'Achmed',
    name2:'Ibn-Leru',
    name3:'',
    fullName:'Larmin Husbow',
  },
  {
    id:0o5,
    factionName:'Dugo',
    factionImageTop:'./assets/images/cardBackgrounds/DugoTop.png',
    factionImageBottom:'./assets/images/cardBackgrounds/DugoBottom.png',
    name1:'Achmed',
    name2:'Ibn-Leru',
    name3:'',
    fullName:'Ruhani Yuni Kalano',
  },
];